dataset_path: 'data'
mixed_data: 'data/mixed'
output_path: 'outputs/matcha_gpt2'   

tokenizer_name: 'gpt2'  
model_name: 'gpt2'

batch_size: 64  
learning_rate: 1e-4  
num_epochs: 15
decay_rate: 0.05
step_size: 10
gamma: 0.1

eval_steps: 1000
margin: 1

seed: 42
contexual_dim: 512
max_samples: 1000000 
